# Generated by Django 3.0.8 on 2020-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200826_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='Your order is on the way', max_length=5000),
        ),
    ]
